CONTENT_TYPE_CONTEXTS: dict[str, str] = {
    "EXERCISE": "C'est un EXERCICE d'entraînement. L'objectif est l'apprentissage et la pratique. Tu peux ajouter des aides, des indices et des guidages car ce n'est pas une évaluation sommative. L'élève a le droit de se tromper et de recommencer. Propose des exemples de réponse quand c'est pertinent.",
    "EVALUATION": "C'est une ÉVALUATION (contrôle, devoir surveillé). L'objectif est de vérifier les acquis. Tu DOIS conserver le même barème et les mêmes compétences évaluées. Tu peux adapter la forme (guidage, format des questions, mise en page) mais PAS le fond. Ne donne pas d'indices qui révèleraient la réponse. Les aides portent sur la MÉTHODE (comment répondre) et non sur le CONTENU (quoi répondre).",
    "LESSON": "C'est une LEÇON ou un COURS. L'objectif est la transmission de connaissances. Tu dois restructurer pour faciliter la compréhension et la mémorisation. Ajoute des résumés, des schémas, des encadrés \"À retenir\". Organise l'information de façon progressive (du simple au complexe). Assure-toi que les définitions clés sont clairement identifiées.",
    "INSTRUCTION": "C'est une CONSIGNE ou un protocole d'activité. L'objectif est que l'élève comprenne exactement ce qu'il doit faire. Décompose en étapes numérotées, clarifie chaque action attendue, ajoute des exemples de ce qui est attendu. Assure-toi que chaque étape est vérifiable.",
    "TEXT": "C'est un TEXTE DOCUMENTAIRE ou littéraire. L'objectif est la compréhension de lecture. Tu dois faciliter l'accès au texte sans le dénaturer. Restructure, aère, explique le vocabulaire, ajoute des repères visuels — mais conserve le contenu informationnel intact. Ne résume pas le texte, adapte sa présentation.",
    "WORKSHEET": "C'est une FICHE DE TRAVAIL ou fiche d'activité. L'objectif est la pratique autonome. Adapte le format pour que l'élève puisse travailler seul : consignes claires, exemples, aides méthodologiques, espaces de réponse adaptés. L'élève doit pouvoir compléter la fiche sans aide supplémentaire d'un adulte.",
    "OTHER": "Le type de contenu n'est pas précisé. Analyse le contenu fourni pour déterminer s'il s'agit plutôt d'un exercice, d'une évaluation, d'une leçon, d'une consigne, d'un texte ou d'une fiche de travail, et adapte ta stratégie en conséquence.",
}
